-- DropForeignKey
ALTER TABLE `don_gia` DROP FOREIGN KEY `DON_GIA_LP_MA_fkey`;

-- AddForeignKey
ALTER TABLE `DON_GIA` ADD CONSTRAINT `DON_GIA_LP_MA_fkey` FOREIGN KEY (`LP_MA`) REFERENCES `LOAI_PHONG`(`LP_MA`) ON DELETE CASCADE ON UPDATE CASCADE;
