-- CreateTable
CREATE TABLE `CT_DAT_TRUOC` (
    `CTDP_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `HDONG_MA` INTEGER NOT NULL,
    `LP_MA` INTEGER NOT NULL,
    `SO_LUONG` INTEGER NOT NULL DEFAULT 1,
    `DON_GIA` DOUBLE NOT NULL DEFAULT 0,
    `TONG_TIEN` DOUBLE NOT NULL DEFAULT 0,
    `TRANG_THAI` VARCHAR(191) NOT NULL DEFAULT 'CONFIRMED',
    `NGAY_TAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`CTDP_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CT_DAT_TRUOC` ADD CONSTRAINT `CT_DAT_TRUOC_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CT_DAT_TRUOC` ADD CONSTRAINT `CT_DAT_TRUOC_LP_MA_fkey` FOREIGN KEY (`LP_MA`) REFERENCES `LOAI_PHONG`(`LP_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;
