-- CreateTable
CREATE TABLE `TANG` (
    `TANG_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `TANG_TEN` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`TANG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOAI_PHONG` (
    `LP_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `LP_TEN` VARCHAR(191) NOT NULL,
    `LP_SONGUOI` INTEGER NOT NULL,

    PRIMARY KEY (`LP_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HINH_THUC_THUE` (
    `HT_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `HT_TEN` VARCHAR(191) NOT NULL,
    `HT_MOTA` VARCHAR(191) NULL,

    UNIQUE INDEX `HINH_THUC_THUE_HT_TEN_key`(`HT_TEN`),
    PRIMARY KEY (`HT_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THOI_DIEM` (
    `TD_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `TD_TEN` VARCHAR(191) NOT NULL,
    `TD_TRANGTHAI` BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (`TD_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THOI_DIEM_BASE` (
    `TD_MA` INTEGER NOT NULL,
    `TD_MOTA_CHUNG` VARCHAR(191) NULL,

    PRIMARY KEY (`TD_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THOI_DIEM_SPECIAL` (
    `TD_MA` INTEGER NOT NULL,
    `TD_NGAY_BAT_DAU` DATETIME(3) NOT NULL,
    `TD_NGAY_KET_THUC` DATETIME(3) NOT NULL,
    `TD_MOTA_CHIENDICH` VARCHAR(191) NULL,

    INDEX `THOI_DIEM_SPECIAL_TD_NGAY_BAT_DAU_TD_NGAY_KET_THUC_idx`(`TD_NGAY_BAT_DAU`, `TD_NGAY_KET_THUC`),
    PRIMARY KEY (`TD_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DON_GIA` (
    `LP_MA` INTEGER NOT NULL,
    `HT_MA` INTEGER NOT NULL,
    `TD_MA` INTEGER NOT NULL,
    `DG_DONGIA` DECIMAL(14, 2) NOT NULL,

    PRIMARY KEY (`LP_MA`, `HT_MA`, `TD_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TIEN_NGHI` (
    `TN_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `TN_TEN` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`TN_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRANGBI_TIENNGHI` (
    `LP_MA` INTEGER NOT NULL,
    `TN_MA` INTEGER NOT NULL,
    `TN_NGAY_TB` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TN_SOLUONG` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`LP_MA`, `TN_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHONG` (
    `PHONG_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `LP_MA` INTEGER NOT NULL,
    `TANG_MA` INTEGER NOT NULL,
    `PHONG_TEN` VARCHAR(191) NOT NULL,
    `PHONG_TRANGTHAI` ENUM('AVAILABLE', 'OCCUPIED', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE',

    UNIQUE INDEX `PHONG_PHONG_TEN_key`(`PHONG_TEN`),
    PRIMARY KEY (`PHONG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LICH_SU_DON_PHONG` (
    `LSDP_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `PHONG_MA` INTEGER NOT NULL,
    `LSDP_TRANGTHAI` ENUM('PENDING', 'IN_PROGRESS', 'DONE', 'CANCELLED') NOT NULL,
    `LSDP_NGAYGIO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `LSDP_GHICHU` VARCHAR(191) NULL,

    PRIMARY KEY (`LSDP_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KHACH_HANG` (
    `KH_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `KH_HOTEN` VARCHAR(191) NOT NULL,
    `KH_NGAYSINH` DATETIME(3) NULL,
    `KH_GIOITINH` VARCHAR(191) NULL,
    `KH_CCCD` VARCHAR(191) NOT NULL,
    `KH_EMAIL` VARCHAR(191) NULL,
    `KH_SDT` VARCHAR(191) NOT NULL,
    `KH_DIACHI` VARCHAR(191) NULL,
    `KH_TAIKHOAN` VARCHAR(191) NULL,
    `KH_MATKHAU` VARCHAR(191) NULL,
    `KH_NGAYTAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `KH_NGAYSUA` DATETIME(3) NOT NULL,

    UNIQUE INDEX `KHACH_HANG_KH_CCCD_key`(`KH_CCCD`),
    UNIQUE INDEX `KHACH_HANG_KH_EMAIL_key`(`KH_EMAIL`),
    UNIQUE INDEX `KHACH_HANG_KH_SDT_key`(`KH_SDT`),
    UNIQUE INDEX `KHACH_HANG_KH_TAIKHOAN_key`(`KH_TAIKHOAN`),
    PRIMARY KEY (`KH_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LUU_TRU_KHACH` (
    `KH_MA` INTEGER NOT NULL,
    `HDONG_MA` INTEGER NOT NULL,
    `LA_KHACH_CHINH` BOOLEAN NOT NULL DEFAULT false,
    `LA_KHACH_DAT` BOOLEAN NOT NULL DEFAULT false,
    `GHI_CHU` VARCHAR(191) NULL,

    INDEX `LUU_TRU_KHACH_KH_MA_idx`(`KH_MA`),
    INDEX `LUU_TRU_KHACH_HDONG_MA_LA_KHACH_CHINH_idx`(`HDONG_MA`, `LA_KHACH_CHINH`),
    INDEX `LUU_TRU_KHACH_HDONG_MA_LA_KHACH_DAT_idx`(`HDONG_MA`, `LA_KHACH_DAT`),
    PRIMARY KEY (`HDONG_MA`, `KH_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `NHAN_VIEN` (
    `NV_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `NV_HOTEN` VARCHAR(191) NOT NULL,
    `NV_EMAIL` VARCHAR(191) NULL,
    `NV_SDT` VARCHAR(191) NOT NULL,
    `NV_NGAYSINH` DATETIME(3) NULL,
    `NV_GIOITINH` VARCHAR(191) NULL,
    `NV_CHUCVU` VARCHAR(191) NOT NULL,
    `NV_TAIKHOAN` VARCHAR(191) NOT NULL,
    `NV_MATKHAU` VARCHAR(191) NOT NULL,
    `NV_TRANGTHAI` VARCHAR(191) NOT NULL DEFAULT 'DANG_LAM',
    `NV_NGAYTAO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `NV_NGAYSUA` DATETIME(3) NOT NULL,

    UNIQUE INDEX `NHAN_VIEN_NV_EMAIL_key`(`NV_EMAIL`),
    UNIQUE INDEX `NHAN_VIEN_NV_SDT_key`(`NV_SDT`),
    UNIQUE INDEX `NHAN_VIEN_NV_TAIKHOAN_key`(`NV_TAIKHOAN`),
    PRIMARY KEY (`NV_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOP_DONG_DAT_PHONG` (
    `HDONG_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `KH_MA` INTEGER NOT NULL,
    `NV_MA` INTEGER NULL,
    `HT_MA` INTEGER NOT NULL,
    `HDONG_NGAYDAT` DATETIME(3) NOT NULL,
    `HDONG_NGAYTRA` DATETIME(3) NOT NULL,
    `HDONG_NGAYTHUCNHAN` DATETIME(3) NULL,
    `HDONG_NGAYTHUCTRA` DATETIME(3) NULL,
    `HDONG_TONGTIENDUKIEN` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    `HDONG_TILECOCAPDUNG` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `HDONG_TIENCOCYEUCAU` DECIMAL(14, 2) NOT NULL DEFAULT 0,
    `HDONG_TRANG_THAI` ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW') NOT NULL DEFAULT 'PENDING',
    `HDONG_TAO_LUC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `HDONG_SUA_LUC` DATETIME(3) NULL,
    `HDONG_GHICHU` VARCHAR(191) NULL,

    INDEX `HOP_DONG_DAT_PHONG_KH_MA_HDONG_TRANG_THAI_idx`(`KH_MA`, `HDONG_TRANG_THAI`),
    INDEX `HOP_DONG_DAT_PHONG_HDONG_NGAYDAT_HDONG_NGAYTRA_idx`(`HDONG_NGAYDAT`, `HDONG_NGAYTRA`),
    PRIMARY KEY (`HDONG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHI_TIET_SU_DUNG` (
    `CTSD_STT` INTEGER NOT NULL,
    `HDONG_MA` INTEGER NOT NULL,
    `PHONG_MA` INTEGER NOT NULL,
    `CTSD_NGAY_DA_O` DATETIME(3) NULL,
    `CTSD_O_TU_GIO` DATETIME(3) NULL,
    `CTSD_O_DEN_GIO` DATETIME(3) NULL,
    `CTSD_SO_LUONG` INTEGER NOT NULL,
    `CTSD_DON_GIA` DECIMAL(12, 2) NOT NULL,
    `CTSD_TONG_TIEN` DECIMAL(12, 2) NOT NULL,
    `CTSD_TRANGTHAI` ENUM('ACTIVE', 'CANCELLED', 'INVOICED') NOT NULL DEFAULT 'ACTIVE',
    `CTSD_HUY_LUC` DATETIME(3) NULL,
    `CTSD_HUY_LYDO` VARCHAR(191) NULL,
    `CTSD_HUY_NV` INTEGER NULL,

    UNIQUE INDEX `uniq_ctsd_night`(`HDONG_MA`, `PHONG_MA`, `CTSD_NGAY_DA_O`),
    UNIQUE INDEX `uniq_ctsd_hour`(`HDONG_MA`, `PHONG_MA`, `CTSD_O_TU_GIO`, `CTSD_O_DEN_GIO`),
    PRIMARY KEY (`HDONG_MA`, `PHONG_MA`, `CTSD_STT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOAI_DICH_VU` (
    `LDV_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `LDV_TEN` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`LDV_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DICH_VU` (
    `DV_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `LDV_MA` INTEGER NOT NULL,
    `DV_TEN` VARCHAR(191) NOT NULL,
    `DV_DONGIA` DECIMAL(12, 2) NOT NULL,

    PRIMARY KEY (`DV_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHI_TIET_DICH_VU` (
    `CTDV_STT` INTEGER NOT NULL,
    `HDONG_MA` INTEGER NOT NULL,
    `PHONG_MA` INTEGER NOT NULL,
    `CTSD_STT` INTEGER NOT NULL,
    `DV_MA` INTEGER NOT NULL,
    `CTDV_NGAY` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `CTDV_SOLUONG` INTEGER NOT NULL,
    `CTDV_DONGIA` DECIMAL(12, 2) NOT NULL,
    `CTDV_GHICHU` VARCHAR(191) NULL,
    `CTDV_TRANGTHAI` ENUM('ACTIVE', 'CANCELLED', 'INVOICED') NOT NULL DEFAULT 'ACTIVE',
    `CTDV_HUY_LUC` DATETIME(3) NULL,
    `CTDV_HUY_LYDO` VARCHAR(191) NULL,
    `CTDV_HUY_NV` INTEGER NULL,
    `pHONGPHONG_MA` INTEGER NULL,
    `hOP_DONG_DAT_PHONGHDONG_MA` INTEGER NULL,

    INDEX `CHI_TIET_DICH_VU_HDONG_MA_PHONG_MA_CTSD_STT_idx`(`HDONG_MA`, `PHONG_MA`, `CTSD_STT`),
    INDEX `CHI_TIET_DICH_VU_DV_MA_CTDV_NGAY_idx`(`DV_MA`, `CTDV_NGAY`),
    INDEX `CHI_TIET_DICH_VU_HDONG_MA_idx`(`HDONG_MA`),
    PRIMARY KEY (`HDONG_MA`, `PHONG_MA`, `CTSD_STT`, `DV_MA`, `CTDV_STT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KHUYEN_MAI` (
    `ID_KM` INTEGER NOT NULL AUTO_INCREMENT,
    `KM_MA` VARCHAR(191) NOT NULL,
    `KM_TEN` VARCHAR(191) NOT NULL,
    `KM_MOTA` VARCHAR(191) NOT NULL,
    `KM_KIEUAPDUNG` ENUM('PERCENT', 'AMOUNT') NOT NULL,
    `KM_GIA_TRI` DECIMAL(12, 2) NOT NULL,
    `KM_TU` DATETIME(3) NOT NULL,
    `KM_DEN` DATETIME(3) NULL,
    `KM_HIEU_LUC` BOOLEAN NOT NULL,

    UNIQUE INDEX `KHUYEN_MAI_KM_MA_key`(`KM_MA`),
    PRIMARY KEY (`ID_KM`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KHUYEN_MAI_SU_DUNG` (
    `ID_KM` INTEGER NOT NULL,
    `HDONG_MA` INTEGER NOT NULL,
    `KM_SOTIEN_GIAM` DECIMAL(12, 2) NOT NULL,
    `KM_NGAY_SD` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `KHUYEN_MAI_SU_DUNG_ID_KM_idx`(`ID_KM`),
    UNIQUE INDEX `KHUYEN_MAI_SU_DUNG_HDONG_MA_key`(`HDONG_MA`),
    PRIMARY KEY (`ID_KM`, `HDONG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DANH_GIA` (
    `DG_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `KH_MA` INTEGER NOT NULL,
    `HDONG_MA` INTEGER NOT NULL,
    `DG_SAO` INTEGER NOT NULL,
    `DG_TIEU_DE` VARCHAR(191) NOT NULL,
    `DG_NOI_DUNG` TEXT NULL,
    `DG_TRANG_THAI` ENUM('PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'PUBLISHED',
    `DG_TAO_LUC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `DANH_GIA_HDONG_MA_DG_TRANG_THAI_idx`(`HDONG_MA`, `DG_TRANG_THAI`),
    UNIQUE INDEX `DANH_GIA_HDONG_MA_key`(`HDONG_MA`),
    PRIMARY KEY (`DG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DINH_KEM_DANH_GIA` (
    `DKDG_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `DG_MA` INTEGER NOT NULL,
    `DKDG_LOAI` ENUM('IMAGE', 'VIDEO') NOT NULL,
    `DKDG_URL` VARCHAR(191) NOT NULL,
    `DKDG_CHUTHICH` VARCHAR(191) NULL,

    PRIMARY KEY (`DKDG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHAN_HOI` (
    `PH_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `DG_MA` INTEGER NOT NULL,
    `NV_MA` INTEGER NOT NULL,
    `PH_NOIDUNG` TEXT NOT NULL,
    `PH_TAO_LUC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `PHAN_HOI_DG_MA_key`(`DG_MA`),
    PRIMARY KEY (`PH_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOA_DON` (
    `HDON_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `NV_MA` INTEGER NOT NULL,
    `HDON_TONG_TIEN` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `HDON_GIAM_GIA` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `HDON_PHI` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `HDON_COC_DA_TRU` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `HDON_THANH_TIEN` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `HDON_CHITIET_JSON` JSON NOT NULL,
    `HDON_TRANG_THAI` ENUM('DRAFT', 'ISSUED', 'PAID', 'VOID') NOT NULL DEFAULT 'ISSUED',
    `HDON_TAO_LUC` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`HDON_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THANH_TOAN` (
    `TT_MA` INTEGER NOT NULL AUTO_INCREMENT,
    `HDON_MA` INTEGER NOT NULL,
    `TT_PHUONG_THUC` ENUM('CASH', 'BANK_QR', 'CARD', 'GATEWAY') NOT NULL,
    `TT_NHA_CUNG_CAP` VARCHAR(191) NULL,
    `TT_TRANG_THAI_GIAO_DICH` ENUM('INITIATED', 'SUCCEEDED', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'INITIATED',
    `TT_SO_TIEN` DECIMAL(12, 2) NOT NULL,
    `TT_SO_TIEN_KHACH_DUA` DECIMAL(12, 2) NULL,
    `TT_TIEN_THUA` DECIMAL(12, 2) NULL,
    `TT_NGAY_GIO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TT_NGAY_CAP_NHAT` DATETIME(3) NOT NULL,
    `TT_MA_GIAO_DICH` VARCHAR(191) NULL,
    `TT_GHI_CHU` VARCHAR(191) NULL,

    INDEX `THANH_TOAN_HDON_MA_TT_TRANG_THAI_GIAO_DICH_idx`(`HDON_MA`, `TT_TRANG_THAI_GIAO_DICH`),
    PRIMARY KEY (`TT_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOA_DON_HOP_DONG` (
    `HDON_MA` INTEGER NOT NULL,
    `HDONG_MA` INTEGER NOT NULL,

    PRIMARY KEY (`HDON_MA`, `HDONG_MA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHAT_SESSION` (
    `ID_SESSION` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_KH` INTEGER NULL,
    `STARTED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID_SESSION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHAT_MESSAGE` (
    `ID_MES` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_SESSION` INTEGER NOT NULL,
    `ROLE` ENUM('user', 'assistant', 'system') NOT NULL,
    `CONTENT` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `CHAT_MESSAGE_ID_SESSION_CREATED_AT_idx`(`ID_SESSION`, `CREATED_AT`),
    PRIMARY KEY (`ID_MES`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KB_DOCUMENT` (
    `ID_DOC` INTEGER NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(191) NULL,
    `SOURCE_URL` VARCHAR(191) NULL,
    `TAGS` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID_DOC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KB_CHUNK` (
    `ID_CHUNK` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DOC` INTEGER NOT NULL,
    `CONTENT` VARCHAR(191) NOT NULL,
    `EMBEDDING_JSON` JSON NOT NULL,
    `TOKEN_COUNT` INTEGER NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `KB_CHUNK_ID_DOC_idx`(`ID_DOC`),
    PRIMARY KEY (`ID_CHUNK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `THOI_DIEM_BASE` ADD CONSTRAINT `THOI_DIEM_BASE_TD_MA_fkey` FOREIGN KEY (`TD_MA`) REFERENCES `THOI_DIEM`(`TD_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THOI_DIEM_SPECIAL` ADD CONSTRAINT `THOI_DIEM_SPECIAL_TD_MA_fkey` FOREIGN KEY (`TD_MA`) REFERENCES `THOI_DIEM`(`TD_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DON_GIA` ADD CONSTRAINT `DON_GIA_LP_MA_fkey` FOREIGN KEY (`LP_MA`) REFERENCES `LOAI_PHONG`(`LP_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DON_GIA` ADD CONSTRAINT `DON_GIA_HT_MA_fkey` FOREIGN KEY (`HT_MA`) REFERENCES `HINH_THUC_THUE`(`HT_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DON_GIA` ADD CONSTRAINT `DON_GIA_TD_MA_fkey` FOREIGN KEY (`TD_MA`) REFERENCES `THOI_DIEM`(`TD_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRANGBI_TIENNGHI` ADD CONSTRAINT `TRANGBI_TIENNGHI_LP_MA_fkey` FOREIGN KEY (`LP_MA`) REFERENCES `LOAI_PHONG`(`LP_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRANGBI_TIENNGHI` ADD CONSTRAINT `TRANGBI_TIENNGHI_TN_MA_fkey` FOREIGN KEY (`TN_MA`) REFERENCES `TIEN_NGHI`(`TN_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHONG` ADD CONSTRAINT `PHONG_LP_MA_fkey` FOREIGN KEY (`LP_MA`) REFERENCES `LOAI_PHONG`(`LP_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHONG` ADD CONSTRAINT `PHONG_TANG_MA_fkey` FOREIGN KEY (`TANG_MA`) REFERENCES `TANG`(`TANG_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LICH_SU_DON_PHONG` ADD CONSTRAINT `LICH_SU_DON_PHONG_PHONG_MA_fkey` FOREIGN KEY (`PHONG_MA`) REFERENCES `PHONG`(`PHONG_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LUU_TRU_KHACH` ADD CONSTRAINT `LUU_TRU_KHACH_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LUU_TRU_KHACH` ADD CONSTRAINT `LUU_TRU_KHACH_KH_MA_fkey` FOREIGN KEY (`KH_MA`) REFERENCES `KHACH_HANG`(`KH_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOP_DONG_DAT_PHONG` ADD CONSTRAINT `HOP_DONG_DAT_PHONG_KH_MA_fkey` FOREIGN KEY (`KH_MA`) REFERENCES `KHACH_HANG`(`KH_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOP_DONG_DAT_PHONG` ADD CONSTRAINT `HOP_DONG_DAT_PHONG_NV_MA_fkey` FOREIGN KEY (`NV_MA`) REFERENCES `NHAN_VIEN`(`NV_MA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOP_DONG_DAT_PHONG` ADD CONSTRAINT `HOP_DONG_DAT_PHONG_HT_MA_fkey` FOREIGN KEY (`HT_MA`) REFERENCES `HINH_THUC_THUE`(`HT_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_SU_DUNG` ADD CONSTRAINT `CHI_TIET_SU_DUNG_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_SU_DUNG` ADD CONSTRAINT `CHI_TIET_SU_DUNG_PHONG_MA_fkey` FOREIGN KEY (`PHONG_MA`) REFERENCES `PHONG`(`PHONG_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_SU_DUNG` ADD CONSTRAINT `CHI_TIET_SU_DUNG_CTSD_HUY_NV_fkey` FOREIGN KEY (`CTSD_HUY_NV`) REFERENCES `NHAN_VIEN`(`NV_MA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DICH_VU` ADD CONSTRAINT `DICH_VU_LDV_MA_fkey` FOREIGN KEY (`LDV_MA`) REFERENCES `LOAI_DICH_VU`(`LDV_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_DV_MA_fkey` FOREIGN KEY (`DV_MA`) REFERENCES `DICH_VU`(`DV_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_HDONG_MA_PHONG_MA_CTSD_STT_fkey` FOREIGN KEY (`HDONG_MA`, `PHONG_MA`, `CTSD_STT`) REFERENCES `CHI_TIET_SU_DUNG`(`HDONG_MA`, `PHONG_MA`, `CTSD_STT`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_CTDV_HUY_NV_fkey` FOREIGN KEY (`CTDV_HUY_NV`) REFERENCES `NHAN_VIEN`(`NV_MA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_pHONGPHONG_MA_fkey` FOREIGN KEY (`pHONGPHONG_MA`) REFERENCES `PHONG`(`PHONG_MA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_hOP_DONG_DAT_PHONGHDONG_MA_fkey` FOREIGN KEY (`hOP_DONG_DAT_PHONGHDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KHUYEN_MAI_SU_DUNG` ADD CONSTRAINT `KHUYEN_MAI_SU_DUNG_ID_KM_fkey` FOREIGN KEY (`ID_KM`) REFERENCES `KHUYEN_MAI`(`ID_KM`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KHUYEN_MAI_SU_DUNG` ADD CONSTRAINT `KHUYEN_MAI_SU_DUNG_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANH_GIA` ADD CONSTRAINT `DANH_GIA_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANH_GIA` ADD CONSTRAINT `DANH_GIA_KH_MA_fkey` FOREIGN KEY (`KH_MA`) REFERENCES `KHACH_HANG`(`KH_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DINH_KEM_DANH_GIA` ADD CONSTRAINT `DINH_KEM_DANH_GIA_DG_MA_fkey` FOREIGN KEY (`DG_MA`) REFERENCES `DANH_GIA`(`DG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHAN_HOI` ADD CONSTRAINT `PHAN_HOI_DG_MA_fkey` FOREIGN KEY (`DG_MA`) REFERENCES `DANH_GIA`(`DG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHAN_HOI` ADD CONSTRAINT `PHAN_HOI_NV_MA_fkey` FOREIGN KEY (`NV_MA`) REFERENCES `NHAN_VIEN`(`NV_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOA_DON` ADD CONSTRAINT `HOA_DON_NV_MA_fkey` FOREIGN KEY (`NV_MA`) REFERENCES `NHAN_VIEN`(`NV_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THANH_TOAN` ADD CONSTRAINT `THANH_TOAN_HDON_MA_fkey` FOREIGN KEY (`HDON_MA`) REFERENCES `HOA_DON`(`HDON_MA`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOA_DON_HOP_DONG` ADD CONSTRAINT `HOA_DON_HOP_DONG_HDON_MA_fkey` FOREIGN KEY (`HDON_MA`) REFERENCES `HOA_DON`(`HDON_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOA_DON_HOP_DONG` ADD CONSTRAINT `HOA_DON_HOP_DONG_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHAT_SESSION` ADD CONSTRAINT `CHAT_SESSION_ID_KH_fkey` FOREIGN KEY (`ID_KH`) REFERENCES `KHACH_HANG`(`KH_MA`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `CHAT_MESSAGE_ID_SESSION_fkey` FOREIGN KEY (`ID_SESSION`) REFERENCES `CHAT_SESSION`(`ID_SESSION`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KB_CHUNK` ADD CONSTRAINT `KB_CHUNK_ID_DOC_fkey` FOREIGN KEY (`ID_DOC`) REFERENCES `KB_DOCUMENT`(`ID_DOC`) ON DELETE RESTRICT ON UPDATE CASCADE;
