-- AlterTable
ALTER TABLE `loai_phong` ADD COLUMN `LP_TRANGTHAI` VARCHAR(191) NOT NULL DEFAULT 'DANG_KINH_DOANH';

-- CreateTable
CREATE TABLE `LOAI_PHONG_IMAGE` (
    `IMG_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `LP_MA` INTEGER NOT NULL,
    `URL` VARCHAR(191) NOT NULL,
    `IS_MAIN` BOOLEAN NOT NULL DEFAULT false,
    `ORD` INTEGER NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`IMG_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `LOAI_PHONG_IMAGE` ADD CONSTRAINT `LOAI_PHONG_IMAGE_LP_MA_fkey` FOREIGN KEY (`LP_MA`) REFERENCES `LOAI_PHONG`(`LP_MA`) ON DELETE CASCADE ON UPDATE CASCADE;
