-- CreateTable
CREATE TABLE `TANG` (
    `ID_TANG` INTEGER NOT NULL AUTO_INCREMENT,
    `TEN_TANG` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_TANG`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOAI_PHONG` (
    `ID_LP` INTEGER NOT NULL AUTO_INCREMENT,
    `TEN_LP` VARCHAR(191) NOT NULL,
    `SONGUOI_LP` INTEGER NOT NULL,

    PRIMARY KEY (`ID_LP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DON_GIA` (
    `ID_DG` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_LP` INTEGER NOT NULL,
    `DG_DONVI` ENUM('DAILY', 'HOURLY') NOT NULL,
    `DG_DONGIA` DECIMAL(12, 2) NOT NULL,
    `DG_NGAYAPDUNG_TU` DATETIME(3) NOT NULL,
    `DG_NGAYAPDUNG_DEN` DATETIME(3) NULL,

    INDEX `DON_GIA_ID_LP_DG_DONVI_DG_NGAYAPDUNG_TU_idx`(`ID_LP`, `DG_DONVI`, `DG_NGAYAPDUNG_TU`),
    UNIQUE INDEX `DON_GIA_ID_LP_DG_DONVI_DG_NGAYAPDUNG_TU_key`(`ID_LP`, `DG_DONVI`, `DG_NGAYAPDUNG_TU`),
    PRIMARY KEY (`ID_DG`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TIEN_NGHI` (
    `ID_TIENNGHI` INTEGER NOT NULL AUTO_INCREMENT,
    `TEN_TIENNGHI` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_TIENNGHI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `TRANGBI_TIENNGHI` (
    `ID_LP` INTEGER NOT NULL,
    `ID_TIENNGHI` INTEGER NOT NULL,
    `NGAY_TB` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SOLUONG_TB` INTEGER NULL DEFAULT 1,

    PRIMARY KEY (`ID_LP`, `ID_TIENNGHI`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PHONG` (
    `ID_PHONG` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_LP` INTEGER NOT NULL,
    `ID_TANG` INTEGER NOT NULL,
    `TEN_PHONG` VARCHAR(191) NOT NULL,
    `TRANGTHAI_PHONG` ENUM('AVAILABLE', 'OCCUPIED', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE',

    PRIMARY KEY (`ID_PHONG`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LICH_SU_DON_PHONG` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_PHONG` INTEGER NOT NULL,
    `TRANG_THAI` ENUM('PENDING', 'IN_PROGRESS', 'DONE', 'CANCELLED') NOT NULL,
    `NGAY_GIO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `GHI_CHU` VARCHAR(191) NULL,

    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHINH_SACH` (
    `ID_CS` INTEGER NOT NULL AUTO_INCREMENT,
    `GIO_CHECKIN` TIME(0) NOT NULL DEFAULT '14:00:00',
    `GIO_CHECKOUT` TIME(0) NOT NULL DEFAULT '12:00:00',
    `TIEN_DAT_COC` DECIMAL(5, 2) NOT NULL DEFAULT 0,
    `PHI_CHECKIN_SOM` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `PHI_CHECKOUT_TRE` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `NGUOI_CAPNHAT` INTEGER NULL,
    `NGAY_CAPNHAT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID_CS`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LP_CHINH_SACH` (
    `ID_LP` INTEGER NOT NULL,
    `KHOA` ENUM('CHECKIN_TIME', 'CHECKOUT_TIME', 'DEPOSIT_PERCENT', 'EARLY_CHECKIN_FEE', 'LATE_CHECKOUT_FEE') NOT NULL,
    `GIA_TRI_GIO` TIME(0) NULL,
    `GIA_TRI_SO` DECIMAL(12, 2) NULL,

    PRIMARY KEY (`ID_LP`, `KHOA`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KHACH_HANG` (
    `ID_KH` INTEGER NOT NULL AUTO_INCREMENT,
    `HOTEN_KH` VARCHAR(191) NOT NULL,
    `SODIENTHOAI_KH` VARCHAR(191) NULL,
    `EMAIL_KH` VARCHAR(191) NULL,
    `DIACHI_KH` VARCHAR(191) NULL,
    `CCCD_KH` VARCHAR(191) NULL,
    `ID_USER` INTEGER NULL,

    UNIQUE INDEX `KHACH_HANG_ID_USER_key`(`ID_USER`),
    PRIMARY KEY (`ID_KH`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `USERS` (
    `ID_USER` INTEGER NOT NULL AUTO_INCREMENT,
    `TEN_USER` VARCHAR(191) NULL,
    `USERNAME` VARCHAR(191) NOT NULL,
    `MATKHAU_USER` VARCHAR(191) NOT NULL,
    `CHUC_VU_USER` ENUM('ADMIN', 'MANAGER', 'RECEPTIONIST', 'GUEST') NOT NULL DEFAULT 'GUEST',

    UNIQUE INDEX `USERS_USERNAME_key`(`USERNAME`),
    PRIMARY KEY (`ID_USER`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOP_DONG_DAT_PHONG` (
    `ID_HOPDONG` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_KH` INTEGER NOT NULL,
    `CREATED_BY_USER_ID` INTEGER NULL,
    `HANDLED_BY_USER_ID` INTEGER NULL,
    `NGAYDAT` DATETIME(3) NOT NULL,
    `NGAYTRA` DATETIME(3) NOT NULL,
    `CHECKIN_AT` DATETIME(3) NULL,
    `CHECKOUT_AT` DATETIME(3) NULL,
    `TRANG_THAI_HDONG` ENUM('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED', 'NO_SHOW') NOT NULL DEFAULT 'PENDING',
    `TAO_NGAY` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SUA_NGAY` DATETIME(3) NULL,
    `GHICHU_HDDV` VARCHAR(191) NULL,

    INDEX `idx_res_guest_status`(`ID_KH`, `TRANG_THAI_HDONG`),
    INDEX `idx_res_dates`(`NGAYDAT`, `NGAYTRA`),
    PRIMARY KEY (`ID_HOPDONG`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHI_TIET_SU_DUNG` (
    `ID_CTDP` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_HOPDONG` INTEGER NOT NULL,
    `ID_PHONG` INTEGER NOT NULL,
    `CTDP_DONVI` ENUM('NIGHT', 'HOUR') NOT NULL,
    `NGAY_DA_O` DATETIME(3) NULL,
    `O_TU_GIO` DATETIME(3) NULL,
    `O_DEN_GIO` DATETIME(3) NULL,
    `SO_LUONG_GIO` INTEGER NOT NULL,
    `DON_GIA_DP` DECIMAL(12, 2) NOT NULL,
    `CTDP_THANH_TIEN` DECIMAL(12, 2) NOT NULL,

    INDEX `CHI_TIET_SU_DUNG_ID_HOPDONG_ID_PHONG_CTDP_DONVI_idx`(`ID_HOPDONG`, `ID_PHONG`, `CTDP_DONVI`),
    PRIMARY KEY (`ID_CTDP`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LOAI_DICH_VU` (
    `ID_LOAIDICHVU` INTEGER NOT NULL AUTO_INCREMENT,
    `TEN_LOAIDICHVU` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`ID_LOAIDICHVU`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `DICH_VU` (
    `ID_DV` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_LOAIDICHVU` INTEGER NOT NULL,
    `TEN_DV` VARCHAR(191) NOT NULL,
    `DONGIA_DV` DECIMAL(12, 2) NOT NULL,
    `GIAVON_DV` DECIMAL(12, 2) NULL,
    `TONKHO_DV` INTEGER NULL,
    `DONVI_DV` VARCHAR(191) NULL,

    PRIMARY KEY (`ID_DV`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHI_TIET_DICH_VU` (
    `ID_HDDV` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_HOPDONG` INTEGER NOT NULL,
    `ID_DV` INTEGER NOT NULL,
    `NGAY_HDDV` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `SOLUONG_HDDV` INTEGER NOT NULL,
    `DONGIA_HDDV` DECIMAL(12, 2) NOT NULL,
    `GHICHU_HDDV` VARCHAR(191) NULL,

    INDEX `CHI_TIET_DICH_VU_ID_HOPDONG_idx`(`ID_HOPDONG`),
    PRIMARY KEY (`ID_HDDV`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOA_DON` (
    `ID_HD` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_USER` INTEGER NOT NULL,
    `TONG_TIEN` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `THANH_TIEN_HDON` DECIMAL(12, 2) NOT NULL DEFAULT 0,
    `TRANG_THAI_HDON` ENUM('DRAFT', 'ISSUED', 'PAID', 'VOID') NOT NULL DEFAULT 'ISSUED',

    PRIMARY KEY (`ID_HD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHI_TIET_HOA_DON` (
    `ID_CTHD` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_HD` INTEGER NOT NULL,
    `LOAI_SP` ENUM('ROOM_CHARGE', 'SERVICE', 'SURCHARGE', 'DISCOUNT', 'DEPOSIT', 'TAX', 'OTHER') NOT NULL,
    `MOTA` VARCHAR(191) NOT NULL,
    `SO_LUONG` INTEGER NOT NULL DEFAULT 1,
    `DON_GIA` DECIMAL(12, 2) NOT NULL,

    INDEX `CHI_TIET_HOA_DON_ID_HD_LOAI_SP_idx`(`ID_HD`, `LOAI_SP`),
    PRIMARY KEY (`ID_CTHD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `THANH_TOAN` (
    `ID_TT` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_HD` INTEGER NOT NULL,
    `TT_PHUONG_THUC` ENUM('CASH', 'BANK_TRANSFER', 'CARD', 'ONLINE') NOT NULL,
    `TT_TRANG_THAI_GIAO_DICH` ENUM('INITIATED', 'SUCCEEDED', 'FAILED', 'REFUNDED') NOT NULL DEFAULT 'SUCCEEDED',
    `TT_SO_TIEN_KHACH_DUA` DECIMAL(12, 2) NOT NULL,
    `TT_NGAY_GIO` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TT_MA_GIAO_DICH` VARCHAR(191) NULL,

    INDEX `THANH_TOAN_ID_HD_TT_TRANG_THAI_GIAO_DICH_idx`(`ID_HD`, `TT_TRANG_THAI_GIAO_DICH`),
    PRIMARY KEY (`ID_TT`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HOA_DON_HOP_DONG` (
    `invoiceId` INTEGER NOT NULL,
    `reservationId` INTEGER NOT NULL,

    PRIMARY KEY (`invoiceId`, `reservationId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHAT_SESSION` (
    `ID_SESSION` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_KH` INTEGER NULL,
    `STARTED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID_SESSION`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `CHAT_MESSAGE` (
    `ID_MES` BIGINT NOT NULL AUTO_INCREMENT,
    `ID_SESSION` INTEGER NOT NULL,
    `ROLE` ENUM('user', 'assistant', 'system') NOT NULL,
    `CONTENT` VARCHAR(191) NOT NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `CHAT_MESSAGE_ID_SESSION_CREATED_AT_idx`(`ID_SESSION`, `CREATED_AT`),
    PRIMARY KEY (`ID_MES`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KB_DOCUMENT` (
    `ID_DOC` INTEGER NOT NULL AUTO_INCREMENT,
    `TITLE` VARCHAR(191) NULL,
    `SOURCE_URL` VARCHAR(191) NULL,
    `TAGS` VARCHAR(191) NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`ID_DOC`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `KB_CHUNK` (
    `ID_CHUNK` INTEGER NOT NULL AUTO_INCREMENT,
    `ID_DOC` INTEGER NOT NULL,
    `CONTENT` VARCHAR(191) NOT NULL,
    `EMBEDDING_JSON` JSON NOT NULL,
    `TOKEN_COUNT` INTEGER NULL,
    `CREATED_AT` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `KB_CHUNK_ID_DOC_idx`(`ID_DOC`),
    PRIMARY KEY (`ID_CHUNK`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `DON_GIA` ADD CONSTRAINT `DON_GIA_ID_LP_fkey` FOREIGN KEY (`ID_LP`) REFERENCES `LOAI_PHONG`(`ID_LP`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRANGBI_TIENNGHI` ADD CONSTRAINT `TRANGBI_TIENNGHI_ID_LP_fkey` FOREIGN KEY (`ID_LP`) REFERENCES `LOAI_PHONG`(`ID_LP`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `TRANGBI_TIENNGHI` ADD CONSTRAINT `TRANGBI_TIENNGHI_ID_TIENNGHI_fkey` FOREIGN KEY (`ID_TIENNGHI`) REFERENCES `TIEN_NGHI`(`ID_TIENNGHI`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHONG` ADD CONSTRAINT `PHONG_ID_LP_fkey` FOREIGN KEY (`ID_LP`) REFERENCES `LOAI_PHONG`(`ID_LP`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PHONG` ADD CONSTRAINT `PHONG_ID_TANG_fkey` FOREIGN KEY (`ID_TANG`) REFERENCES `TANG`(`ID_TANG`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LICH_SU_DON_PHONG` ADD CONSTRAINT `LICH_SU_DON_PHONG_ID_PHONG_fkey` FOREIGN KEY (`ID_PHONG`) REFERENCES `PHONG`(`ID_PHONG`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHINH_SACH` ADD CONSTRAINT `CHINH_SACH_NGUOI_CAPNHAT_fkey` FOREIGN KEY (`NGUOI_CAPNHAT`) REFERENCES `USERS`(`ID_USER`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `LP_CHINH_SACH` ADD CONSTRAINT `LP_CHINH_SACH_ID_LP_fkey` FOREIGN KEY (`ID_LP`) REFERENCES `LOAI_PHONG`(`ID_LP`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KHACH_HANG` ADD CONSTRAINT `KHACH_HANG_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOP_DONG_DAT_PHONG` ADD CONSTRAINT `HOP_DONG_DAT_PHONG_ID_KH_fkey` FOREIGN KEY (`ID_KH`) REFERENCES `KHACH_HANG`(`ID_KH`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOP_DONG_DAT_PHONG` ADD CONSTRAINT `HOP_DONG_DAT_PHONG_CREATED_BY_USER_ID_fkey` FOREIGN KEY (`CREATED_BY_USER_ID`) REFERENCES `USERS`(`ID_USER`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOP_DONG_DAT_PHONG` ADD CONSTRAINT `HOP_DONG_DAT_PHONG_HANDLED_BY_USER_ID_fkey` FOREIGN KEY (`HANDLED_BY_USER_ID`) REFERENCES `USERS`(`ID_USER`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_SU_DUNG` ADD CONSTRAINT `CHI_TIET_SU_DUNG_ID_HOPDONG_fkey` FOREIGN KEY (`ID_HOPDONG`) REFERENCES `HOP_DONG_DAT_PHONG`(`ID_HOPDONG`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_SU_DUNG` ADD CONSTRAINT `CHI_TIET_SU_DUNG_ID_PHONG_fkey` FOREIGN KEY (`ID_PHONG`) REFERENCES `PHONG`(`ID_PHONG`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DICH_VU` ADD CONSTRAINT `DICH_VU_ID_LOAIDICHVU_fkey` FOREIGN KEY (`ID_LOAIDICHVU`) REFERENCES `LOAI_DICH_VU`(`ID_LOAIDICHVU`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_ID_HOPDONG_fkey` FOREIGN KEY (`ID_HOPDONG`) REFERENCES `HOP_DONG_DAT_PHONG`(`ID_HOPDONG`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_DICH_VU` ADD CONSTRAINT `CHI_TIET_DICH_VU_ID_DV_fkey` FOREIGN KEY (`ID_DV`) REFERENCES `DICH_VU`(`ID_DV`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOA_DON` ADD CONSTRAINT `HOA_DON_ID_USER_fkey` FOREIGN KEY (`ID_USER`) REFERENCES `USERS`(`ID_USER`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHI_TIET_HOA_DON` ADD CONSTRAINT `CHI_TIET_HOA_DON_ID_HD_fkey` FOREIGN KEY (`ID_HD`) REFERENCES `HOA_DON`(`ID_HD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `THANH_TOAN` ADD CONSTRAINT `THANH_TOAN_ID_HD_fkey` FOREIGN KEY (`ID_HD`) REFERENCES `HOA_DON`(`ID_HD`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOA_DON_HOP_DONG` ADD CONSTRAINT `HOA_DON_HOP_DONG_invoiceId_fkey` FOREIGN KEY (`invoiceId`) REFERENCES `HOA_DON`(`ID_HD`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HOA_DON_HOP_DONG` ADD CONSTRAINT `HOA_DON_HOP_DONG_reservationId_fkey` FOREIGN KEY (`reservationId`) REFERENCES `HOP_DONG_DAT_PHONG`(`ID_HOPDONG`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHAT_SESSION` ADD CONSTRAINT `CHAT_SESSION_ID_KH_fkey` FOREIGN KEY (`ID_KH`) REFERENCES `KHACH_HANG`(`ID_KH`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `CHAT_MESSAGE_ID_SESSION_fkey` FOREIGN KEY (`ID_SESSION`) REFERENCES `CHAT_SESSION`(`ID_SESSION`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `KB_CHUNK` ADD CONSTRAINT `KB_CHUNK_ID_DOC_fkey` FOREIGN KEY (`ID_DOC`) REFERENCES `KB_DOCUMENT`(`ID_DOC`) ON DELETE RESTRICT ON UPDATE CASCADE;
