-- DropForeignKey
ALTER TABLE `chat_message` DROP FOREIGN KEY `CHAT_MESSAGE_ID_SESSION_fkey`;

-- AddForeignKey
ALTER TABLE `DANH_GIA` ADD CONSTRAINT `DANH_GIA_HDONG_MA_fkey` FOREIGN KEY (`HDONG_MA`) REFERENCES `HOP_DONG_DAT_PHONG`(`HDONG_MA`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `DANH_GIA` ADD CONSTRAINT `DANH_GIA_CTDP_ID_fkey` FOREIGN KEY (`CTDP_ID`) REFERENCES `CT_DAT_TRUOC`(`CTDP_ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `CHAT_MESSAGE` ADD CONSTRAINT `CHAT_MESSAGE_ID_SESSION_fkey` FOREIGN KEY (`ID_SESSION`) REFERENCES `CHAT_SESSION`(`ID_SESSION`) ON DELETE CASCADE ON UPDATE CASCADE;
