-- DropForeignKey
ALTER TABLE `don_gia` DROP FOREIGN KEY `DON_GIA_TD_MA_fkey`;

-- DropIndex
DROP INDEX `DON_GIA_TD_MA_fkey` ON `don_gia`;

-- AddForeignKey
ALTER TABLE `DON_GIA` ADD CONSTRAINT `DON_GIA_TD_MA_fkey` FOREIGN KEY (`TD_MA`) REFERENCES `THOI_DIEM`(`TD_MA`) ON DELETE CASCADE ON UPDATE CASCADE;
